### PR TITLE
Update test.php

### PR DESCRIPTION
**Pull request by uarora1997**
Hey interested in collaborating on this.

Please do drop your email in comment or where we can chat :)
Regards

### CODE REVIEW

**Comment by PineappleSoftUK** [comment]
Thanks for the interest, this is just something I am messing around with at the moment and I don't think I'm ready for collaboration I'm sorry, but please feel free to keep an eye on my progress and maybe keep in touch in the future. Thanks.

**Comment by uarora1997** [comment]
Hey thank you so much for replying! Yeah totally get it!

Though we are already working on appointment scheduler with laravel as
backend , thought you might be interested!

Please let me know if you have time and may want to come onboard! :)

**Comment by PineappleSoftUK** [comment]
Thanks. If time permits in the future I will get in touch.

**Comment by uarora1997** [comment]
Okay thanks! Have a good day.

**Pull request closed without merging**
